[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
py_version = 310
line_length = 100
remove_redundant_aliases = true
multi_line_output = 4  # vertical grid
float_to_top = true
